### ISSUE TITLE
GSSOC'23: Crop Recommendation using regression

### ISSUE THREAD

**Issue by Shubhamkumar-op** [The-Data-Alchemists-Manipal/MindWave#129] opened 2023-05-22 15:30 UTC
## 💥 Proposal

Prerequisites

- I am GSSOC'23 Contributor

Description

- This project aim to help the farmers to decides which crop they have to grow in the particular condition and environment 
-  It helps the farmers to get informed decision about the farming strategy
- I will use logistic regression model to train the data
- The data I will be using is [https://www.kaggle.com/datasets/atharvaingle/crop-recommendation-dataset](https://www.kaggle.com/datasets/atharvaingle/crop-recommendation-dataset)

@khusheekapoor I  would like to work upon this , please assign it to me

**Comment by 15IITian** [comment] 2023-05-24 04:30
I would love to work on this , Please assign it to me.

**Comment by asthabarwal** [comment] 2023-05-25 03:21
@khusheekapoor I would like to work on this project using this dataset: https://www.kaggle.com/datasets/atharvaingle/crop-recommendation-dataset
I would be using logistic regression for this case. 
Please assign this issue to me.

**Comment by theyashwanthsai** [comment] 2023-05-25 13:36
@15IITian @asthabarwal since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm on a different dataset.

**Closed** 2023-06-11 07:31 UTC
Labels: machine-learning
