### ISSUE TITLE
Salary Prediction

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [The-Data-Alchemists-Manipal/MindWave#179] opened 2023-05-24 12:31 UTC
## 💥 Proposal

Salary Prediction using machine learning algorithms

**Comment by Vethan123** [comment] 2023-05-25 10:40
Hi @Soumya-Kushwaha ,I think I can work on this because my previous project is somewhat related to this.please assign it to me

**Comment by asthabarwal** [comment] 2023-05-25 16:38
Hey @khusheekapoor @Soumya-Kushwaha I would love to work on this issue. I am planning to achieve salary prediction model using Linear regression or decision tree algorithm.
The dataset i will be using is this : https://www.kaggle.com/datasets/thedevastator/jobs-dataset-from-glassdoor
Please assign this issue to me.

**Comment by theyashwanthsai** [comment] 2023-05-25 18:43
@Vethan123 @asthabarwal since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm on a different dataset.

**Comment by theyashwanthsai** [comment] 2023-05-25 18:44
@Soumya-Kushwaha please provide us with the algorithm which you will be using and the dataset link. Thank you

**Comment by khusheekapoor** [comment] 2023-05-27 18:12
@Soumya-Kushwaha - you can go ahead! We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best! 
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

**Closed** 2023-06-11 07:36 UTC
Labels: machine-learning
