### ISSUE TITLE
💥Proposal for Logistic Regression on the Credit Card Fraud Dataset

### ISSUE THREAD

**Issue by dibyarupnath** [The-Data-Alchemists-Manipal/MindWave#14] opened 2023-05-19 19:19 UTC
## 💥 Proposal

To implement the Logistic Regression algorithm on the Credit Card Fraud Dataset.
Link to the Dataset: https://www.kaggle.com/datasets/dhanushnarayananr/credit-card-fraud

I would like to work on this project for Logistic Regression. But I need to start working on it **post 7 June**, due to my end semester exams. I will try to work on the LeNet issue in the next 21 days, by taking breaks between my studies.

**Comment by s0oraj** [comment] 2023-05-20 02:30
Hi @dibyarupnath  , iam a GSSOC23 contributer and I would like to resolve this issue

Can you assign me this issue? Or any other issues you might have?
Heres My Resume which you might find useful: [Resume](https://github.com/s0oraj/Animus/files/11521330/Resume.pdf)
Here is my background in ML:

1) 6 months plus experience in working under college professors for research project on medical image classification.
2) Got 228 global rank in Amazon ML Challenge 2023 out of 30000+ teams participating.
3) Experienced with trainig machine Learning Models. Including image preprocessing techniues such as histrogram equilization, augmentation, stationary wavelet transformation, image segmentation. Along with feature extraction from models like resnet50 inceptionv3 vgg16 etc

Looking forward to hear from you.

**Comment by ASHWIN492** [comment] 2023-05-20 03:57
Hi @dibyarupnath , I am a GSSOC23 contributor and I would like to resolve this issue. can you assign me

**Comment by khusheekapoor** [comment] 2023-05-20 04:41
Hi @dibyarupnath, this sounds like a great idea! You can go ahead :)
We are assigning you 21 days for this project, after which it will be assigned to someone else if not completed. All the best!
Name the file as: `algorithm_dataset.ipynb` and link it in the readme of the labeled directory as `algorithm - dataset`.

@ASHWIN492 @s0oraj - since we are following the first-come-first-serve policy, we will not be able to assign you this issue. However, you can create another issue and use the same algorithm (logistic regression) on a different dataset.

**Comment by UditSharma9999** [comment] 2023-05-20 16:46
I'm a contributor for GSSoC '23, I want to work on this issue. Please assign me.

**Comment by dibyarupnath** [comment] 2023-06-11 07:22
@khusheekapoor I made the pull requests for this task and LeNet on the MNIST Dataset (#9) before the due date, however there is some merge conflict on the readme file, is it okay if I close the pull requests and make a new one for these 2 tasks with the conflicts resolved? I will have to pull the latest changes to the readme file and update it with my repo links.

**Closed** 2023-06-11 07:35 UTC
Labels: machine-learning, gssoc23, level2
